-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 20:37:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
  `idturmas` INT NOT NULL,
  `turno` VARCHAR(10) NOT NULL,
  `número` CHAR(3) NULL,
  PRIMARY KEY (`idturmas`, `turno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `idalunos` INT NOT NULL,
  `data de nascimento` DATE NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `turmas_idturmas` INT NOT NULL,
  `turmas_turno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalunos`),
  INDEX `fk_alunos_turmas_idx` (`turmas_idturmas` ASC, `turmas_turno` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_turmas`
    FOREIGN KEY (`turmas_idturmas` , `turmas_turno`)
    REFERENCES `mydb`.`turmas` (`idturmas` , `turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `idcursos` INT NOT NULL,
  `Requisitos` VARCHAR(45) NULL,
  `Tempo (meses)` CHAR(2) NULL,
  `turmas_idturmas` INT NOT NULL,
  `turmas_turno` VARCHAR(45) NOT NULL,
  INDEX `fk_cursos_turmas1_idx` (`turmas_idturmas` ASC, `turmas_turno` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_turmas1`
    FOREIGN KEY (`turmas_idturmas` , `turmas_turno`)
    REFERENCES `mydb`.`turmas` (`idturmas` , `turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
